version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - CERTS:/etc/nginx/certs:ro
      - VHOST:/etc/nginx/vhost.d
      - HTML:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - default

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - CERTS:/etc/nginx/certs:rw
      - VHOST:/etc/nginx/vhost.d
      - HTML:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

networks:
  default:

volumes:
  CERTS:
  VHOST:
  HTML:
